import {
  Activity,
  Cable,
  Cpu,
  Gauge,
  Home,
  Lightbulb,
  Monitor,
  Network,
  Power,
  Radio,
  Server,
  SlidersHorizontal,
  ToggleLeft,
  Waves,
  Wind,
} from "lucide-react";
import type { Product } from "@/types/content";

const common = {
  lifecycle: "Engineering sample; specifications finalized per program",
  support: "Documentation and integration support available",
};

export const products: Product[] = [
  {
    slug: "industrial-iot-gateway",
    name: "Industrial IoT Gateway",
    category: "Industrial Computing",
    summary: "Secure protocol aggregation and edge connectivity for brownfield equipment.",
    description: "A configurable gateway platform for connecting machines, sensors, and field networks to modern data systems.",
    features: ["Multi-protocol field connectivity", "Local rules and data buffering", "Secure remote management", "DIN-rail deployment"],
    applications: ["Machine monitoring", "Legacy equipment integration", "Remote asset visibility"],
    specifications: { Processor: "Application-class ARM platform", Interfaces: "Ethernet, RS485, configurable wireless", Software: "Embedded Linux", Lifecycle: common.lifecycle },
    accent: "from-cyan-500/30 to-blue-700/10",
    icon: Network,
    featured: true,
  },
  {
    slug: "smart-energy-meter",
    name: "Smart Energy Meter",
    category: "Power & Energy",
    summary: "Connected electrical measurement for buildings and distributed equipment.",
    description: "A compact metering platform designed for accurate telemetry, local integration, and cloud-connected energy applications.",
    features: ["Real-time electrical telemetry", "Configurable reporting", "RS485 and wireless variants", "Event and threshold monitoring"],
    applications: ["Energy dashboards", "Equipment sub-metering", "Building management"],
    specifications: { Measurement: "Program-specific single or three phase", Protocols: "Modbus RTU, MQTT options", Mounting: "Panel or DIN rail options", Support: common.support },
    accent: "from-amber-400/30 to-orange-700/10",
    icon: Gauge,
    featured: true,
  },
  {
    slug: "industrial-controller",
    name: "Industrial Controller",
    category: "Industrial Computing",
    summary: "Flexible real-time control core for machines and distributed systems.",
    description: "An embedded controller family combining deterministic I/O, industrial networking, and configurable application software.",
    features: ["Real-time control architecture", "Expandable digital and analog I/O", "Industrial network options", "Protected power input"],
    applications: ["Machine control", "Process skids", "Distributed automation"],
    specifications: { Compute: "MCU or Linux variants", IO: "Program-configurable", Networks: "CAN, RS485, Ethernet options", Lifecycle: common.lifecycle },
    accent: "from-sky-400/30 to-indigo-700/10",
    icon: Cpu,
    featured: true,
  },
  {
    slug: "plc-module",
    name: "PLC Module",
    category: "Industrial Computing",
    summary: "Compact modular I/O and control for tailored automation systems.",
    description: "A scalable PLC-oriented module platform supporting configurable control, communication, and expansion requirements.",
    features: ["Modular I/O architecture", "IEC-oriented control options", "Fast fieldbus communication", "Serviceable terminal design"],
    applications: ["Panel automation", "Material handling", "Test equipment"],
    specifications: { IO: "Digital, analog, relay variants", Bus: "RS485, CAN, Ethernet options", Installation: "DIN rail", Support: common.support },
    accent: "from-blue-500/30 to-slate-700/10",
    icon: SlidersHorizontal,
  },
  {
    slug: "embedded-controller-board",
    name: "Embedded Controller Board",
    category: "Industrial Computing",
    summary: "Customizable compute foundation for OEM equipment.",
    description: "A board-level platform engineered around the thermal, mechanical, connectivity, and lifecycle needs of the end product.",
    features: ["MCU and MPU options", "Custom carrier and I/O", "Boot and security architecture", "Manufacturing test support"],
    applications: ["OEM equipment", "Connected appliances", "Specialized instrumentation"],
    specifications: { Silicon: "ESP32, STM32, NXP or application MPU", Design: "Custom or semi-custom", Software: "RTOS or Embedded Linux", Lifecycle: common.lifecycle },
    accent: "from-emerald-500/25 to-cyan-700/10",
    icon: Cpu,
  },
  {
    slug: "industrial-power-supply",
    name: "Industrial Power Supply",
    category: "Power & Energy",
    summary: "Efficient, protected conversion for embedded and control systems.",
    description: "Program-specific AC/DC and DC/DC power solutions engineered for stable operation and integration into industrial products.",
    features: ["Protected input and output", "Thermal-aware design", "Low-noise options", "Design-for-test provisions"],
    applications: ["Control panels", "Embedded equipment", "Distributed electronics"],
    specifications: { Topology: "Application dependent", Input: "AC/DC or DC/DC variants", Protection: "Program-specific protection set", Compliance: "Evaluated for target market requirements" },
    accent: "from-yellow-400/30 to-red-700/10",
    icon: Power,
  },
  {
    slug: "rs485-device",
    name: "RS485 Device",
    category: "Industrial Communication",
    summary: "Reliable field communication endpoint for sensors and controls.",
    description: "A rugged wired device platform for Modbus and proprietary serial networks in electrically demanding environments.",
    features: ["Isolated interface options", "Configurable address and baud rate", "Field-upgradeable firmware", "Compact enclosure options"],
    applications: ["Remote I/O", "Sensor networks", "Building controls"],
    specifications: { Physical: "RS485", Protocol: "Modbus RTU or custom", Power: "Application dependent", Support: common.support },
    accent: "from-violet-500/25 to-blue-700/10",
    icon: Cable,
  },
  {
    slug: "industrial-communication-module",
    name: "Industrial Communication Module",
    category: "Industrial Communication",
    summary: "Drop-in connectivity for products requiring industrial protocols.",
    description: "A module family that accelerates the integration of fieldbus, Ethernet, serial, and wireless communication.",
    features: ["Protocol-ready firmware", "Host API", "Isolation options", "Reference integration design"],
    applications: ["OEM controllers", "Drive systems", "Instrumentation"],
    specifications: { Interfaces: "CAN, RS485, Ethernet or wireless", Host: "UART, SPI, USB or Ethernet", Form: "Board or enclosed module", Lifecycle: common.lifecycle },
    accent: "from-indigo-500/25 to-cyan-700/10",
    icon: Network,
  },
  {
    slug: "wireless-module",
    name: "Wireless Module",
    category: "Industrial Communication",
    summary: "Integrated wireless building block for connected products.",
    description: "A compact radio and firmware platform supporting secure onboarding, application communication, and lifecycle updates.",
    features: ["Wi-Fi and BLE options", "Secure device identity", "Reference antenna guidance", "OTA-ready architecture"],
    applications: ["Connected devices", "Retrofit modules", "Telemetry endpoints"],
    specifications: { Wireless: "Wi-Fi and Bluetooth LE variants", Host: "UART, SPI, or standalone", Security: "Hardware-backed options", Support: common.support },
    accent: "from-fuchsia-500/20 to-blue-700/10",
    icon: Radio,
  },
  {
    slug: "edge-ai-gateway",
    name: "Edge AI Gateway",
    category: "Industrial Computing",
    summary: "Local inference and industrial data processing near the source.",
    description: "An application-class edge platform for workloads where latency, privacy, resilience, or bandwidth demand local intelligence.",
    features: ["Accelerated inference options", "Containerized application support", "Industrial I/O", "Remote fleet operations"],
    applications: ["Visual inspection", "Predictive monitoring", "Operational analytics"],
    specifications: { Compute: "ARM or x86 platform options", Acceleration: "Program-specific AI accelerator", Software: "Embedded Linux", Connectivity: "Ethernet, serial, wireless options" },
    accent: "from-purple-500/30 to-cyan-700/10",
    icon: Server,
    featured: true,
  },
  {
    slug: "smart-home-gateway",
    name: "Smart Home Gateway",
    category: "Smart Home",
    summary: "Local coordination for responsive, private connected living.",
    description: "A multi-radio home platform that unifies devices, scenes, cloud services, and local automations.",
    features: ["Local automation engine", "Multi-radio options", "Secure cloud bridge", "Managed OTA updates"],
    applications: ["Whole-home automation", "Property platforms", "OEM ecosystems"],
    specifications: { Compute: "Embedded Linux platform", Radios: "Wi-Fi, BLE, Thread or Zigbee options", API: "Local and cloud integration", Support: common.support },
    accent: "from-teal-400/30 to-cyan-800/10",
    icon: Home,
  },
  {
    slug: "matter-hub",
    name: "Matter Hub",
    category: "Smart Home",
    summary: "Interoperable device coordination for modern smart-home ecosystems.",
    description: "A Matter-oriented hub platform supporting commissioning, local control, and bridges to established device networks.",
    features: ["Matter controller architecture", "Thread border-router option", "Local scene execution", "Diagnostics and lifecycle management"],
    applications: ["Residential platforms", "Hospitality rooms", "Property automation"],
    specifications: { Standards: "Matter and Thread options", Backhaul: "Ethernet or Wi-Fi", Management: "Local and cloud", Lifecycle: common.lifecycle },
    accent: "from-cyan-400/30 to-violet-700/10",
    icon: Waves,
  },
  {
    slug: "smart-switch",
    name: "Smart Switch",
    category: "Smart Home",
    summary: "Premium connected switching with dependable local behavior.",
    description: "A modular wall-switch family balancing tactile quality, modern connectivity, and installation practicality.",
    features: ["Local control without cloud dependency", "Scene and schedule support", "Multi-gang platform", "OTA-ready firmware"],
    applications: ["Homes", "Hospitality", "Smart buildings"],
    specifications: { Variants: "One to four gang concepts", Connectivity: "Wi-Fi, BLE or Matter program options", Input: "Market-specific power architecture", Status: "Program-specific product development" },
    accent: "from-cyan-400/30 to-slate-700/10",
    icon: ToggleLeft,
    featured: true,
  },
  {
    slug: "smart-dimmer",
    name: "Smart Dimmer",
    category: "Smart Home",
    summary: "Connected lighting control with smooth, configurable response.",
    description: "A dimming control platform engineered around lamp compatibility, thermal performance, and intuitive operation.",
    features: ["Configurable dimming range", "Local and remote operation", "Scene integration", "Thermal monitoring options"],
    applications: ["Residential lighting", "Hospitality", "Ambience control"],
    specifications: { Load: "Program-specific lighting compatibility", Control: "Touch, button, app, automation", Connectivity: "Wireless variants", Compliance: "Evaluated for target market requirements" },
    accent: "from-amber-300/30 to-orange-700/10",
    icon: Lightbulb,
  },
  {
    slug: "smart-fan-controller",
    name: "Smart Fan Controller",
    category: "Smart Home",
    summary: "Connected speed control designed for regional fan systems.",
    description: "A purpose-built controller for fan speed, automation, and app integration with market-specific electrical design.",
    features: ["Multi-step speed control", "Local manual operation", "Schedules and scenes", "Thermal protection options"],
    applications: ["Homes", "Hospitality", "Retrofit projects"],
    specifications: { Control: "Multi-speed program options", Connectivity: "Wi-Fi or Matter options", Input: "Market-specific", Status: "Program-specific product development" },
    accent: "from-sky-300/30 to-blue-700/10",
    icon: Wind,
  },
  {
    slug: "curtain-controller",
    name: "Curtain Controller",
    category: "Smart Home",
    summary: "Precise motorized shade and curtain automation.",
    description: "A compact embedded controller for directional motor control, position workflows, and smart-home integration.",
    features: ["Open, close, and stop control", "Calibration workflow", "Scene and schedule support", "Manual input compatibility"],
    applications: ["Curtains", "Blinds", "Motorized shades"],
    specifications: { Motor: "Application-specific AC or DC variants", Inputs: "Local switch inputs", Connectivity: "Wireless program options", Support: common.support },
    accent: "from-rose-400/20 to-violet-700/10",
    icon: SlidersHorizontal,
  },
  {
    slug: "wifi-relay",
    name: "Wi-Fi Relay",
    category: "Smart Home",
    summary: "Compact connected actuation for retrofit and embedded control.",
    description: "A relay module designed to add secure remote operation, schedules, and automation to existing electrical products.",
    features: ["Compact module architecture", "Local input support", "Schedules and timers", "Secure onboarding"],
    applications: ["Retrofit control", "OEM appliances", "Lighting and pumps"],
    specifications: { Outputs: "Single or multi-channel options", Wireless: "2.4 GHz Wi-Fi and BLE provisioning", Input: "Program-specific", Status: "Program-specific product development" },
    accent: "from-blue-400/30 to-cyan-800/10",
    icon: ToggleLeft,
  },
  {
    slug: "ble-gateway",
    name: "BLE Gateway",
    category: "Industrial Communication",
    summary: "Managed Bluetooth device collection and cloud forwarding.",
    description: "A configurable gateway for scanning, connecting, filtering, and forwarding Bluetooth Low Energy device data.",
    features: ["Concurrent scanning workflows", "Edge filtering", "Secure backhaul", "Remote configuration"],
    applications: ["Asset tracking", "Sensor collection", "Retail infrastructure"],
    specifications: { Radio: "Bluetooth Low Energy", Backhaul: "Ethernet, Wi-Fi or cellular options", Software: "Managed Linux or RTOS", Support: common.support },
    accent: "from-blue-500/30 to-violet-700/10",
    icon: Radio,
  },
  {
    slug: "zigbee-gateway",
    name: "Zigbee Gateway",
    category: "Smart Home",
    summary: "Local Zigbee coordination for devices, scenes, and cloud platforms.",
    description: "A robust coordinator platform supporting OEM device ecosystems and bridges into modern home applications.",
    features: ["Local device coordination", "Scene execution", "Cloud bridge APIs", "Fleet diagnostics"],
    applications: ["Smart home platforms", "Lighting systems", "Property automation"],
    specifications: { Radio: "Zigbee program options", Backhaul: "Ethernet or Wi-Fi", API: "OEM-specific integration", Lifecycle: common.lifecycle },
    accent: "from-emerald-400/30 to-cyan-700/10",
    icon: Network,
  },
  {
    slug: "touch-panel",
    name: "Touch Panel",
    category: "Interfaces & Sensing",
    summary: "Premium local interface for rooms, equipment, and connected spaces.",
    description: "A configurable display and touch platform combining a focused user experience with local system integration.",
    features: ["Custom interface design", "Capacitive touch", "Local control integration", "Wall or panel mounting"],
    applications: ["Room controls", "Machine interfaces", "Building systems"],
    specifications: { Display: "Program-specific size and technology", Touch: "Capacitive options", Software: "RTOS or Embedded Linux", Interfaces: "Ethernet, RS485, wireless options" },
    accent: "from-slate-300/20 to-cyan-700/10",
    icon: Monitor,
  },
  {
    slug: "smart-sensor",
    name: "Smart Sensor",
    category: "Interfaces & Sensing",
    summary: "Connected environmental and occupancy sensing platform.",
    description: "A low-power sensor architecture configurable around environmental, motion, and equipment-monitoring requirements.",
    features: ["Multi-sensor options", "Low-power architecture", "Local threshold logic", "Wireless reporting"],
    applications: ["Smart buildings", "Equipment monitoring", "Home automation"],
    specifications: { Sensing: "Environmental, motion or application-specific", Wireless: "BLE, Zigbee, Thread or Wi-Fi options", Power: "Battery or wired variants", Support: common.support },
    accent: "from-green-400/25 to-cyan-700/10",
    icon: Activity,
  },
  {
    slug: "industrial-display",
    name: "Industrial Display",
    category: "Interfaces & Sensing",
    summary: "Purpose-engineered visualization for equipment and control environments.",
    description: "A display subsystem integrating panel, electronics, enclosure, and software around the target operating environment.",
    features: ["Display and touch options", "Custom mechanical integration", "Wide input interface options", "Application-specific UI support"],
    applications: ["Machine HMI", "Instrumentation", "Information terminals"],
    specifications: { Panel: "Program-specific size and brightness", Input: "HDMI, LVDS, MIPI or embedded compute", Touch: "Optional capacitive interface", Lifecycle: common.lifecycle },
    accent: "from-zinc-300/20 to-blue-700/10",
    icon: Monitor,
  },
];

export const productCategories = [...new Set(products.map((product) => product.category))];

export const getProduct = (slug: string) => products.find((product) => product.slug === slug);
